window.TEXTFIT_PRESETS = [
  {
    id: "youtube-title",
    slug: "youtube-title-length-checker",
    category: "Global",
    platform: "YouTube",
    field: "Video title",
    label: "YouTube title",
    limit: 100,
    unit: "chars",
    type: "Verified limit",
    hint: "YouTube Data API documents a 100 character maximum for video titles.",
    sourceName: "YouTube Data API",
    sourceUrl: "https://developers.google.com/youtube/v3/docs/videos#snippet.title",
    example: "Turn messy screenshots into clean launch graphics"
  },
  {
    id: "youtube-description",
    slug: "youtube-description-length-checker",
    category: "Global",
    platform: "YouTube",
    field: "Video description",
    label: "YouTube description",
    limit: 5000,
    unit: "bytes",
    type: "Verified limit",
    hint: "The API limit is measured in bytes, which matters for CJK text and emoji.",
    sourceName: "YouTube Data API",
    sourceUrl: "https://developers.google.com/youtube/v3/docs/videos#snippet.description",
    example: "A short summary, links, credits, timestamps, and notes for viewers."
  },
  {
    id: "google-ads-headline",
    slug: "google-ads-headline-character-counter",
    category: "Global",
    platform: "Google Ads",
    field: "Responsive search ad headline",
    label: "Google Ads headline",
    limit: 30,
    unit: "weighted",
    type: "Verified limit",
    hint: "Google Ads counts Korean, Japanese, and Chinese double-width characters as 2.",
    sourceName: "Google Ads Help",
    sourceUrl: "https://support.google.com/google-ads/answer/7684791",
    example: "Resize Images Online"
  },
  {
    id: "google-ads-description",
    slug: "google-ads-description-character-counter",
    category: "Global",
    platform: "Google Ads",
    field: "Responsive search ad description",
    label: "Google Ads description",
    limit: 90,
    unit: "weighted",
    type: "Verified limit",
    hint: "Use this for ad descriptions where CJK characters need double-width counting.",
    sourceName: "Google Ads Help",
    sourceUrl: "https://support.google.com/google-ads/answer/7684791",
    example: "Crop, resize, and convert images in your browser before uploading."
  },
  {
    id: "app-store-name",
    slug: "app-store-name-length-checker",
    category: "Global",
    platform: "App Store",
    field: "App name",
    label: "App Store name",
    limit: 30,
    unit: "chars",
    type: "Verified limit",
    hint: "Apple documents a 2 to 30 character range for localized app names.",
    sourceName: "App Store Connect Help",
    sourceUrl: "https://developer.apple.com/help/app-store-connect/reference/app-information/app-information",
    example: "TextFit"
  },
  {
    id: "app-store-subtitle",
    slug: "app-store-subtitle-length-checker",
    category: "Global",
    platform: "App Store",
    field: "Subtitle",
    label: "App Store subtitle",
    limit: 30,
    unit: "chars",
    type: "Verified limit",
    hint: "Apple documents a 30 character maximum for subtitles.",
    sourceName: "App Store Connect Help",
    sourceUrl: "https://developer.apple.com/help/app-store-connect/reference/app-information/app-information",
    example: "Copy length checks"
  },
  {
    id: "meta-title",
    slug: "meta-title-length-checker",
    category: "SEO",
    platform: "Search",
    field: "Meta title",
    label: "Meta title",
    recommendedMin: 45,
    recommendedMax: 60,
    unit: "chars",
    type: "Practical range",
    hint: "Search engines do not promise one fixed title length. This range is a practical writing target.",
    sourceName: "Google Search Central",
    sourceUrl: "https://developers.google.com/search/docs/appearance/title-link",
    example: "TextFit - Platform Character Counter"
  },
  {
    id: "meta-description",
    slug: "meta-description-length-checker",
    category: "SEO",
    platform: "Search",
    field: "Meta description",
    label: "Meta description",
    recommendedMin: 120,
    recommendedMax: 160,
    unit: "chars",
    type: "Practical range",
    hint: "A concise description is easier to reuse in search results and AI summaries.",
    sourceName: "Google Search Central",
    sourceUrl: "https://developers.google.com/search/docs/appearance/snippet",
    example: "TextFit checks copy length for platform fields, ads, metadata, and CJK-heavy writing."
  },
  {
    id: "x-post",
    slug: "x-post-character-counter",
    category: "Global",
    platform: "X",
    field: "Post",
    label: "X post",
    limit: 280,
    unit: "weighted",
    type: "Platform style count",
    hint: "TextFit uses weighted counting so CJK-heavy posts show the tighter 140-character feel.",
    sourceName: "X Developer docs",
    sourceUrl: "https://docs.x.com/",
    example: "A small tool can win when the next action is obvious."
  },
  {
    id: "note-title",
    slug: "note-title-character-counter",
    category: "Japan",
    platform: "note",
    field: "Article title",
    label: "note title",
    recommendedMin: 24,
    recommendedMax: 40,
    unit: "chars",
    type: "Writing guide",
    hint: "A compact title is easier to scan in note feeds and social previews.",
    sourceName: "note Help",
    sourceUrl: "https://www.help-note.com/",
    example: "画像を投稿サイズに整える小さな道具"
  },
  {
    id: "qiita-title",
    slug: "qiita-title-length-checker",
    category: "Japan",
    platform: "Qiita",
    field: "Article title",
    label: "Qiita title",
    recommendedMin: 28,
    recommendedMax: 60,
    unit: "chars",
    type: "Writing guide",
    hint: "Technical titles usually need room for the problem, stack, and outcome.",
    sourceName: "Qiita Help",
    sourceUrl: "https://help.qiita.com/",
    example: "Cloudflare Pagesで小さな静的ツールを公開する"
  },
  {
    id: "zenn-title",
    slug: "zenn-title-length-checker",
    category: "Japan",
    platform: "Zenn",
    field: "Article title",
    label: "Zenn title",
    recommendedMin: 28,
    recommendedMax: 60,
    unit: "chars",
    type: "Writing guide",
    hint: "Use this as a readable range for development notes and tutorials.",
    sourceName: "Zenn Guide",
    sourceUrl: "https://zenn.dev/zenn/articles",
    example: "ブラウザだけでPDFを画像に変換する"
  },
  {
    id: "xiaohongshu-title",
    slug: "xiaohongshu-title-counter",
    category: "China",
    platform: "Xiaohongshu",
    field: "Note title",
    label: "Xiaohongshu title",
    recommendedMin: 12,
    recommendedMax: 24,
    unit: "chars",
    type: "Writing guide",
    hint: "Shorter titles usually scan better in discovery feeds. Treat this as a writing target, not a platform guarantee.",
    sourceName: "Xiaohongshu Help",
    sourceUrl: "https://www.xiaohongshu.com/",
    example: "一键裁好头像比例"
  },
  {
    id: "wechat-title",
    slug: "wechat-article-title-counter",
    category: "China",
    platform: "WeChat",
    field: "Article title",
    label: "WeChat article title",
    recommendedMin: 16,
    recommendedMax: 32,
    unit: "chars",
    type: "Writing guide",
    hint: "This range keeps titles readable in chats, subscriptions, and forwarded previews.",
    sourceName: "WeChat Official Accounts Platform",
    sourceUrl: "https://mp.weixin.qq.com/",
    example: "我把图片工具做成了浏览器版本"
  },
  {
    id: "bilibili-title",
    slug: "bilibili-title-counter",
    category: "China",
    platform: "Bilibili",
    field: "Video title",
    label: "Bilibili title",
    recommendedMin: 18,
    recommendedMax: 42,
    unit: "chars",
    type: "Writing guide",
    hint: "Use enough detail for search while keeping the title readable in feeds.",
    sourceName: "Bilibili Creator Center",
    sourceUrl: "https://member.bilibili.com/",
    example: "做一个浏览器里的PDF转换工具"
  },
  {
    id: "douyin-title",
    slug: "douyin-title-counter",
    category: "China",
    platform: "Douyin",
    field: "Video caption",
    label: "Douyin caption",
    recommendedMin: 10,
    recommendedMax: 40,
    unit: "chars",
    type: "Writing guide",
    hint: "A compact first line helps viewers understand the video before expanding the caption.",
    sourceName: "Douyin Creator Service",
    sourceUrl: "https://creator.douyin.com/",
    example: "这个图片裁剪工具终于顺手了"
  }
];

window.TEXTFIT_BY_SLUG = Object.fromEntries(window.TEXTFIT_PRESETS.map((preset) => [preset.slug, preset]));
window.TEXTFIT_BY_ID = Object.fromEntries(window.TEXTFIT_PRESETS.map((preset) => [preset.id, preset]));
